begin;

alter table public.projects
  add column if not exists id_bigint bigint generated by default as identity;

alter table public.project_categories
  add column if not exists project_id_bigint bigint;

alter table public.project_votes
  add column if not exists project_id_bigint bigint;

update public.project_categories as pc
set project_id_bigint = p.id_bigint
from public.projects as p
where pc.project_id = p.id
  and pc.project_id_bigint is null;

update public.project_votes as pv
set project_id_bigint = p.id_bigint
from public.projects as p
where pv.project_id = p.id
  and pv.project_id_bigint is null;

alter table public.project_categories
  alter column project_id_bigint set not null;

alter table public.project_votes
  alter column project_id_bigint set not null;

alter table public.project_categories
  drop constraint if exists project_categories_project_id_fkey;

alter table public.project_votes
  drop constraint if exists project_votes_project_id_fkey;

alter table public.project_categories
  drop constraint if exists project_categories_pkey;

alter table public.project_votes
  drop constraint if exists project_votes_pkey;

alter table public.projects
  drop constraint if exists projects_pkey;

alter table public.project_categories
  drop column if exists project_id;

alter table public.project_votes
  drop column if exists project_id;

alter table public.projects
  drop column if exists id;

alter table public.projects
  rename column id_bigint to id;

alter table public.project_categories
  rename column project_id_bigint to project_id;

alter table public.project_votes
  rename column project_id_bigint to project_id;

alter table public.projects
  add constraint projects_pkey primary key (id);

alter table public.project_categories
  add constraint project_categories_pkey primary key (project_id, category_id);

alter table public.project_votes
  add constraint project_votes_pkey primary key (project_id, user_id);

alter table public.project_categories
  add constraint project_categories_project_id_fkey
  foreign key (project_id) references public.projects(id) on delete cascade;

alter table public.project_votes
  add constraint project_votes_project_id_fkey
  foreign key (project_id) references public.projects(id) on delete cascade;

create unique index if not exists projects_id_key on public.projects (id);

commit;
